---
- name: ensure nftables conf directory exists
  file:
    path: /etc/nftables
    state: directory
    owner: root
    group: root
    mode: 0755

- name: configure nftables rules
  template:
    src: etc/nftables/nftables.conf.j2
    dest: /etc/nftables/nftables.conf
    owner: root
    group: root
    mode: 0644
    validate: nft -c -f %s
  notify:
    - reload nftables

- name: ensure nftables.service.d directory exists
  file:
    path: /etc/systemd/system/nftables.service.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: configure nftables.service override
  template:
    src: etc/systemd/system/nftables.service.d/override.conf.j2
    dest: /etc/systemd/system/nftables.service.d/override.conf
    owner: root
    group: root
    mode: 0644
