---
- name: get all available services
  service_facts:

- name: remove firewalld
  block:
    - name: disable and mask firewalld
      systemd:
        name: firewalld.service
        state: stopped
        enabled: no
        masked: yes

    - name: remove firewalld package
      package:
        name: firewalld
        state: absent
  when: "'firewalld.service' in ansible_facts.services"

- name: remove ufw (uncompilcated firewall)
  block:
    - name: disable and mask ufw
      systemd:
        name: ufw.service
        state: stopped
        enabled: no
        masked: yes

    - name: remove ufw package
      package:
        name: ufw
        state: absent
  when: "'ufw.service' in ansible_facts.services"
